export type {
  LifecyclePhase,
  LifecycleContext,
  PipelineStage,
  PipelineContext,
  PipelineOptions,
  NexocHooks,
  NexocHookable,
  Command,
  CommandMeta,
  CommandOptions,
  CommandArgs,
  CommandOptionDef,
  CommandArgDef,
  CommandContext,
  BuildAdapter,
  BuildOptions,
  BuildResult,
  AdapterRegistry,
  NexocConfig,
  NexocPlugin,
  NexocInstance,
} from '@nexoc/types'

